name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Laravel PHPUnit
      # You may pin to the exact commit or the version.
      # uses: nathanheffley/laravel-phpunit-action@1ac680fbc5f20621343f0d7ba450a02b807c576e
        uses: nathanheffley/laravel-phpunit-action@v0.1.0
    
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Deploy Laravel BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server generated
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/imageuploader.juggyprojects.com/
            rm -r /var/www/imageuploader.juggyprojects.com/Dev-Challenges-ImageUploader-Laravel-BE
            git clone git@github.com:JUGG097/Dev-Challenges-ImageUploader-Laravel-BE.git
            cd Dev-Challenges-ImageUploader-Laravel-BE
            composer install --optimize-autoloader --no-dev
            cp /var/www/imageuploader.juggyprojects.com/.env /var/www/imageuploader.juggyprojects.com/Dev-Challenges-ImageUploader-Laravel-BE/.env
            chmod o+w ./storage/ -R
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            systemctl reload nginx
            echo 'Deployment successful to digital ocean'
