name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Laravel BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server generated
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/imageuploader.juggyprojects.com/
            cp git clone git@github.com:JUGG097/Dev-Challenges-ImageUploader-Laravel-BE.git
            cd Dev-Challenges-ImageUploader-Laravel-BE
            composer install
            echo 'Deployment successful to digital ocean'
