name: Build & Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Laravel Tests
        # You may pin to the exact commit or the version.
        # uses: hdev14/laravel-test-action@7dab92e8d7ae9f2c45c86f9061a4e8d0e80bb064
        uses: hdev14/laravel-test-action@v1
    
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Deploy Laravel BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server generated
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/imageuploader.juggyprojects.com/
            rm -r /var/www/imageuploader.juggyprojects.com/Dev-Challenges-ImageUploader-Laravel-BE
            git clone git@github.com:JUGG097/Dev-Challenges-ImageUploader-Laravel-BE.git
            cd Dev-Challenges-ImageUploader-Laravel-BE
            composer install --optimize-autoloader --no-dev
            cp /var/www/imageuploader.juggyprojects.com/.env /var/www/imageuploader.juggyprojects.com/Dev-Challenges-ImageUploader-Laravel-BE/.env
            chmod o+w ./storage/ -R
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            systemctl reload nginx
            echo 'Deployment successful to digital ocean'
